/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionRouteImport } from './routes/session'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DiscussionsRouteImport } from './routes/discussions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsRoute = DiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-tools': typeof AiToolsRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/discussions': typeof DiscussionsRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-tools': typeof AiToolsRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/discussions': typeof DiscussionsRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-tools': typeof AiToolsRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/discussions': typeof DiscussionsRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/session': typeof SessionRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-tools'
    | '/community'
    | '/courses'
    | '/dashboard'
    | '/discussions'
    | '/documents'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/session'
    | '/settings'
    | '/signup'
    | '/upload'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-tools'
    | '/community'
    | '/courses'
    | '/dashboard'
    | '/discussions'
    | '/documents'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/session'
    | '/settings'
    | '/signup'
    | '/upload'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/ai-tools'
    | '/community'
    | '/courses'
    | '/dashboard'
    | '/discussions'
    | '/documents'
    | '/login'
    | '/notes'
    | '/onboarding'
    | '/session'
    | '/settings'
    | '/signup'
    | '/upload'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiToolsRoute: typeof AiToolsRoute
  CommunityRoute: typeof CommunityRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  DiscussionsRoute: typeof DiscussionsRoute
  DocumentsRoute: typeof DocumentsRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  OnboardingRoute: typeof OnboardingRoute
  SessionRoute: typeof SessionRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  UploadRoute: typeof UploadRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions': {
      id: '/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof DiscussionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiToolsRoute: AiToolsRoute,
  CommunityRoute: CommunityRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  DiscussionsRoute: DiscussionsRoute,
  DocumentsRoute: DocumentsRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  OnboardingRoute: OnboardingRoute,
  SessionRoute: SessionRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  UploadRoute: UploadRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
